name: Run Tests

on:
  pull_request:
    types: [opened, reopened, edited]
  workflow_call:

concurrency:
  group: "${{ github.event.pull_request.head.ref }}-test"
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Set up staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Formatting Check
        run: staticcheck $(go list ./...)

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
